[package]
name = "cove-util"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { workspace = true, features = ["serde"] }
rand = { workspace = true }
hex = { workspace = true }
uniffi = { workspace = true, features = ["tokio"] }

