[package]
name = "cove-tokio-ext"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = { workspace = true }
tokio = { workspace = true, features = ["time", "rt"] }
tracing = { workspace = true }
