[package]
name = "cove-tokio"
version = "0.1.0"
edition = "2024"

[dependencies]
act-zero = { version = "0.4.0", features = ["default-tokio"] }
arc-swap = { workspace = true }
futures = "0.3.30"
tokio = { workspace = true, features = ["time", "rt"] }
tracing = { workspace = true }
